"""Acceptance tests for AC-38: Web shell and management screens against frozen contracts.

Acceptance criteria (plan/acceptance.json -> AC-38):
- Requests conform to the frozen contract.
- Empty/loading/validation/conflict states and accessible controls work.
- Tests identify mocks and do not claim connected backend acceptance.
- Strings conform to specs/04-ui.md: "No sales data", "Stock unknown", "Insufficient comparison data".
"""

import json
from pathlib import Path
from storeops_contracts.models import (
    StoreCreate,
    StoreUpdate,
    ProductCreate,
    ProductUpdate,
    PromotionCreate,
    ApprovePolicy,
    Rule,
    PolicySource,
    Kind5,
    Kind4,
    ZoneKind,
    Error,
)


WEB_SRC_DIR = Path("apps/web/src")


def test_ac38_web_directory_structure_exists():
    """Verify that apps/web source structure and core route directories exist."""
    assert WEB_SRC_DIR.exists(), "apps/web/src directory must exist"
    
    expected_dirs = [
        WEB_SRC_DIR / "app",
        WEB_SRC_DIR / "app" / "(auth)" / "sign-in",
        WEB_SRC_DIR / "app" / "(dashboard)" / "setup",
        WEB_SRC_DIR / "app" / "(dashboard)" / "stores",
        WEB_SRC_DIR / "app" / "(dashboard)" / "catalog",
        WEB_SRC_DIR / "app" / "(dashboard)" / "imports",
        WEB_SRC_DIR / "app" / "(dashboard)" / "promotions",
        WEB_SRC_DIR / "components",
        WEB_SRC_DIR / "lib",
    ]
    for d in expected_dirs:
        assert d.exists(), f"Required web directory {d} must exist"


def test_ac38_test_doubles_transparency_and_identification():
    """Verify that API doubles in apps/web/src/lib/doubles.ts are explicitly identified as mocks.
    
    Spec: Tests and components identify mocks and do not claim connected backend acceptance.
    """
    doubles_file = WEB_SRC_DIR / "lib" / "doubles.ts"
    assert doubles_file.exists(), "apps/web/src/lib/doubles.ts must exist"
    
    content = doubles_file.read_text(encoding="utf-8")
    
    # Must explicitly state that this is an isolated test double
    assert "IS_TEST_DOUBLE = true" in content or "isDouble: true" in content or "IS_MOCK = true" in content, (
        "Test doubles must explicitly declare mock/double flag"
    )
    assert "Do not claim connected backend acceptance" in content or "test double only" in content.lower(), (
        "Must document that doubles do not constitute live backend acceptance"
    )


def test_ac38_contract_conformance_for_management_requests():
    """Verify that request objects generated by web client conform strictly to OpenAPI models."""
    # Store creation request
    store_req = StoreCreate(
        code="STR-001",
        name="Marina Bay Supermarket",
        retailer="ColdStorage",
        format="HYPERMARKET",
        region="South",
        timezone="Asia/Singapore",
        distributor_location_id=None,
    )
    dumped = store_req.model_dump(mode="json")
    assert dumped["name"] == "Marina Bay Supermarket"
    assert dumped["timezone"] == "Asia/Singapore"

    # Store update with expected_version (required for conflict detection)
    store_update = StoreUpdate(
        name="Marina Bay Supermarket - North Wing",
        active=True,
        timezone="Asia/Singapore",
        expected_version=1,
    )
    assert store_update.expected_version == 1

    # Product creation request
    prod_req = ProductCreate(
        sku="BEV-SPRITE-330",
        name="Sprite 330ml Can",
        case_units=24,
    )
    assert prod_req.case_units == 24

    # Promotion approval request with valid Rule models
    approve_req = ApprovePolicy(
        expected_version=1,
        catalog_product_ids=["33333333-3333-3333-3333-333333333333"],
        rules=[
            Rule(
                rule_id="aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                kind=Kind5.MIN_FACINGS,
                zone_id="shelf-main",
                zone_kind=ZoneKind.SHELF,
                product_id="33333333-3333-3333-3333-333333333333",
                min_facings=3,
                source=PolicySource(
                    kind=Kind4.DOCUMENT,
                    media_id="bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
                    page=1,
                    quote="Maintain at least 3 facings on primary shelf.",
                    reviewer_note=None,
                ),
            )
        ],
    )
    assert len(approve_req.rules) == 1
    assert approve_req.rules[0].min_facings == 3


def test_ac38_empty_states_and_null_semantics():
    """Verify that management screens and presentation logic use the exact required strings.
    
    From specs/04-ui.md:
    - No sales is “No sales data”, not zero sales.
    - Missing stock is “Stock unknown”, not out of stock.
    - A null opportunity proxy is “Insufficient comparison data”, not SGD 0.00.
    """
    formatters_file = WEB_SRC_DIR / "lib" / "formatters.ts"
    assert formatters_file.exists(), "apps/web/src/lib/formatters.ts must exist"
    content = formatters_file.read_text(encoding="utf-8")

    assert "No sales data" in content, "Must implement 'No sales data' for null sales"
    assert "Stock unknown" in content, "Must implement 'Stock unknown' for missing stock"
    assert "Insufficient comparison data" in content, "Must implement 'Insufficient comparison data' for null opportunity"
    assert "Needs data" in content or "Insufficient comparison data" in content


def test_ac38_version_conflict_error_handling():
    """Verify that HTTP 409 VERSION_CONFLICT is handled with user warning and state refresh guidance."""
    client_file = WEB_SRC_DIR / "lib" / "api-client.ts"
    assert client_file.exists(), "apps/web/src/lib/api-client.ts must exist"
    content = client_file.read_text(encoding="utf-8")

    assert "VERSION_CONFLICT" in content, "API client must detect and handle VERSION_CONFLICT"
    assert "409" in content, "Must handle HTTP 409 conflict status"


def test_ac38_accessible_controls_and_responsive_markup():
    """Verify that web components follow accessibility guidelines and lack fixed overflow widths.
    
    From specs/04-ui.md:
    - At 375 px and desktop widths, the main flow has no horizontal page overflow.
    - Inputs have labels, focus states, keyboard operation and text equivalents for status colors.
    """
    components_dir = WEB_SRC_DIR / "components"
    assert components_dir.exists(), "apps/web/src/components must exist"

    # Inspect all TSX files in components
    tsx_files = list(components_dir.glob("**/*.tsx"))
    assert len(tsx_files) > 0, "There should be component files in apps/web/src/components"

    combined_code = "\n".join(f.read_text(encoding="utf-8") for f in tsx_files)

    # Check for accessibility patterns
    has_labels_or_aria = "aria-label" in combined_code or "htmlFor" in combined_code
    assert has_labels_or_aria, "Components must use aria-label or htmlFor for input associations"

    has_sr_only_or_aria = "sr-only" in combined_code or "aria-live" in combined_code or "role=" in combined_code
    assert has_sr_only_or_aria, "Components must provide text equivalents for visual/status indicators"


def test_ac38_role_based_access_control():
    """Verify that the web shell provides ADMIN vs REP distinction and guards management actions."""
    auth_file = WEB_SRC_DIR / "lib" / "auth-context.tsx"
    assert auth_file.exists(), "apps/web/src/lib/auth-context.tsx must exist"
    content = auth_file.read_text(encoding="utf-8")

    assert "ADMIN" in content and "REP" in content, "Auth context must support ADMIN and REP roles"
    assert "isAdmin" in content or "hasRole" in content, "Auth context must expose role evaluation helper"
