# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-09-16T05:53:56+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr,
)


class Detail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: constr(min_length=1, max_length=100) | None
    message: constr(min_length=1, max_length=500)


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: constr(min_length=1, max_length=80)
    message: constr(min_length=1, max_length=1000)
    request_id: UUID
    details: list[Detail] = Field(..., max_length=50, min_length=0)


class Status(Enum):
    READY = 'READY'
    DEGRADED = 'DEGRADED'


class Profile(Enum):
    LOCAL = 'LOCAL'
    CLOUD = 'CLOUD'


class AiMode(Enum):
    LIVE = 'LIVE'
    STUB = 'STUB'


class Health(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status
    profile: Profile
    ai_mode: AiMode


class Role(Enum):
    ADMIN = 'ADMIN'
    REP = 'REP'


class Membership(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    workspace_id: UUID
    workspace_name: constr(min_length=1, max_length=200)
    role: Role


class Me(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uid: constr(min_length=1, max_length=200)
    memberships: list[Membership] = Field(..., max_length=100, min_length=0)


class Currency(Enum):
    SGD = 'SGD'
    USD = 'USD'
    AUD = 'AUD'


class Workspace(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    workspace_id: UUID
    version: conint(ge=1)
    created_at: AwareDatetime
    updated_at: AwareDatetime
    name: constr(min_length=1, max_length=200)
    brand_name: constr(min_length=1, max_length=200)
    currency: Currency


class StoreCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$')
    name: constr(min_length=1, max_length=200)
    retailer: constr(min_length=1, max_length=200)
    region: constr(min_length=1, max_length=200)
    format: constr(min_length=1, max_length=80)
    timezone: constr(min_length=1, max_length=80)
    distributor_location_id: UUID | None


class StoreUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expected_version: conint(ge=1)
    name: constr(min_length=1, max_length=200) | None = None
    retailer: constr(min_length=1, max_length=200) | None = None
    region: constr(min_length=1, max_length=200) | None = None
    format: constr(min_length=1, max_length=80) | None = None
    timezone: constr(min_length=1, max_length=80) | None = None
    distributor_location_id: UUID | None = None
    active: bool | None = None


class Store(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    workspace_id: UUID
    version: conint(ge=1)
    created_at: AwareDatetime
    updated_at: AwareDatetime
    code: constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$')
    name: constr(min_length=1, max_length=200)
    retailer: constr(min_length=1, max_length=200)
    region: constr(min_length=1, max_length=200)
    format: constr(min_length=1, max_length=80)
    timezone: constr(min_length=1, max_length=80)
    distributor_location_id: UUID | None
    currency: Currency
    backroom_location_id: UUID
    active: bool


class Type(Enum):
    DISTRIBUTOR = 'DISTRIBUTOR'


class LocationCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$')
    name: constr(min_length=1, max_length=200)
    type: Type


class LocationUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expected_version: conint(ge=1)
    name: constr(min_length=1, max_length=200) | None = None
    active: bool | None = None


class Type1(Enum):
    BACKROOM = 'BACKROOM'
    DISTRIBUTOR = 'DISTRIBUTOR'


class Location(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    workspace_id: UUID
    version: conint(ge=1)
    created_at: AwareDatetime
    updated_at: AwareDatetime
    code: constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$')
    name: constr(min_length=1, max_length=200)
    type: Type1
    store_id: UUID | None
    active: bool


class ProductCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sku: constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$')
    name: constr(min_length=1, max_length=200)
    case_units: conint(ge=1, le=10000)


class ProductUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expected_version: conint(ge=1)
    name: constr(min_length=1, max_length=200) | None = None
    case_units: conint(ge=1, le=10000) | None = None
    reference_media_ids: list[UUID] | None = Field(None, max_length=4, min_length=0)
    active: bool | None = None


class Product(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    workspace_id: UUID
    version: conint(ge=1)
    created_at: AwareDatetime
    updated_at: AwareDatetime
    sku: constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$')
    name: constr(min_length=1, max_length=200)
    case_units: conint(ge=1, le=10000)
    reference_media_ids: list[UUID] = Field(..., max_length=4, min_length=0)
    active: bool


class Kind(Enum):
    PRODUCT_REFERENCE = 'PRODUCT_REFERENCE'
    VISIT_BEFORE = 'VISIT_BEFORE'
    VISIT_AFTER = 'VISIT_AFTER'
    AGREEMENT = 'AGREEMENT'
    IMPORT = 'IMPORT'


class MimeType(Enum):
    image_jpeg = 'image/jpeg'
    image_png = 'image/png'
    application_pdf = 'application/pdf'
    text_csv = 'text/csv'


class ZoneKind(Enum):
    SHELF = 'SHELF'
    DISPLAY = 'DISPLAY'


class MediaInit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    filename: constr(min_length=1, max_length=255)
    mime_type: MimeType
    byte_size: conint(ge=1, le=10485760)
    sha256: constr(pattern=r'^[a-f0-9]{64}$')
    store_id: UUID | None
    visit_id: UUID | None
    product_id: UUID | None
    zone_id: constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$') | None
    zone_kind: ZoneKind | None
    captured_at: AwareDatetime | None


class VersionCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expected_version: conint(ge=1)


class Status1(Enum):
    PENDING_UPLOAD = 'PENDING_UPLOAD'
    READY = 'READY'
    REJECTED = 'REJECTED'


class Media(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    workspace_id: UUID
    version: conint(ge=1)
    created_at: AwareDatetime
    updated_at: AwareDatetime
    kind: Kind
    filename: constr(min_length=1, max_length=255)
    mime_type: constr(min_length=1, max_length=100)
    status: Status1
    store_id: UUID | None
    visit_id: UUID | None
    product_id: UUID | None
    zone_id: constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$') | None
    zone_kind: ZoneKind | None
    captured_at: AwareDatetime | None
    original_sha256: constr(pattern=r'^[a-f0-9]{64}$')
    normalized_sha256: constr(pattern=r'^[a-f0-9]{64}$') | None
    byte_size: conint(ge=0)
    width: conint(ge=0) | None
    height: conint(ge=0) | None
    rejection: Error | None
    download_url: AnyUrl | None
    download_url_expires_at: AwareDatetime | None


class Method(Enum):
    PUT = 'PUT'


class MediaUpload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    media: Media
    upload_url: AnyUrl
    method: Method
    headers: dict[str, str]
    expires_at: AwareDatetime


class Type2(Enum):
    IMPORT_VALIDATE = 'IMPORT_VALIDATE'
    IMPORT_COMMIT = 'IMPORT_COMMIT'
    POLICY_EXTRACT = 'POLICY_EXTRACT'
    INVESTIGATE = 'INVESTIGATE'
    VERIFY = 'VERIFY'


class Status2(Enum):
    QUEUED = 'QUEUED'
    RUNNING = 'RUNNING'
    RETRY_WAIT = 'RETRY_WAIT'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'


class ResourceType(Enum):
    IMPORT = 'IMPORT'
    PROMOTION = 'PROMOTION'
    INVESTIGATION = 'INVESTIGATION'
    VERIFICATION = 'VERIFICATION'


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_tokens: conint(ge=0)
    output_tokens: conint(ge=0)
    cost_usd: constr(pattern=r'^-?\d+(\.\d+)?$') | None


class Job(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    workspace_id: UUID
    version: conint(ge=1)
    created_at: AwareDatetime
    updated_at: AwareDatetime
    type: Type2
    status: Status2
    resource_id: UUID
    resource_type: ResourceType
    attempt: conint(ge=0)
    stage: constr(min_length=1, max_length=100) | None
    started_at: AwareDatetime | None
    finished_at: AwareDatetime | None
    error: Error | None
    linked_previous_job_id: UUID | None
    model_id: constr(min_length=1, max_length=100) | None
    usage: Usage | None


class JobEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sequence: conint(ge=1)
    job_id: UUID
    at: AwareDatetime
    stage: constr(min_length=1, max_length=100)
    summary: constr(min_length=1, max_length=500)
    status: Status2


class JobEvents(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[JobEvent] = Field(..., max_length=200, min_length=0)
    last_sequence: conint(ge=0)


class Kind2(Enum):
    SALES = 'SALES'
    INVENTORY = 'INVENTORY'


class ImportCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind2
    media_id: UUID


class ImportError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    row: conint(ge=1)
    field: constr(min_length=1, max_length=100)
    code: constr(min_length=1, max_length=80)
    message: constr(min_length=1, max_length=500)


class Status4(Enum):
    VALIDATING = 'VALIDATING'
    INVALID = 'INVALID'
    VALIDATED = 'VALIDATED'
    COMMITTING = 'COMMITTING'
    COMMITTED = 'COMMITTED'
    FAILED = 'FAILED'


class Import(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    workspace_id: UUID
    version: conint(ge=1)
    created_at: AwareDatetime
    updated_at: AwareDatetime
    kind: Kind2
    media_id: UUID
    status: Status4
    row_count: conint(ge=0)
    error_count: conint(ge=0)
    errors: list[ImportError] = Field(..., max_length=50, min_length=0)
    batch_id: UUID | None
    committed_at: AwareDatetime | None
    source_sha256: constr(pattern=r'^[a-f0-9]{64}$')


class Kind4(Enum):
    DOCUMENT = 'DOCUMENT'
    MANUAL = 'MANUAL'


class PolicySource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind4
    media_id: UUID | None
    page: conint(ge=1, le=10) | None
    quote: constr(min_length=1, max_length=2000) | None
    reviewer_note: constr(min_length=1, max_length=1000) | None


class Kind5(Enum):
    MIN_FACINGS = 'MIN_FACINGS'
    REQUIRED_PRODUCT = 'REQUIRED_PRODUCT'
    REQUIRED_DISPLAY = 'REQUIRED_DISPLAY'


class Rule(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rule_id: UUID
    kind: Kind5
    zone_id: constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$')
    zone_kind: ZoneKind
    product_id: UUID | None
    min_facings: conint(ge=1, le=100) | None
    source: PolicySource


class PolicyVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    promotion_id: UUID
    version: conint(ge=1)
    rules: list[Rule] = Field(..., max_length=30, min_length=1)
    catalog_product_ids: list[UUID] = Field(..., max_length=25, min_length=1)
    store_ids: list[UUID] = Field(..., max_length=1000, min_length=1)
    starts_on: date
    ends_on: date
    approved_at: AwareDatetime
    approved_by: constr(min_length=1, max_length=200)
    content_sha256: constr(pattern=r'^[a-f0-9]{64}$')


class PromotionCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1, max_length=200)
    starts_on: date
    ends_on: date
    store_ids: list[UUID] = Field(..., max_length=1000, min_length=1)
    agreement_media_id: UUID | None


class PromotionUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expected_version: conint(ge=1)
    name: constr(min_length=1, max_length=200) | None = None
    starts_on: date | None = None
    ends_on: date | None = None
    store_ids: list[UUID] | None = Field(None, max_length=1000, min_length=1)
    agreement_media_id: UUID | None = None
    archived: bool | None = None


class ExtractionGap(RootModel[constr(min_length=1, max_length=500)]):
    root: constr(min_length=1, max_length=500)


class Promotion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    workspace_id: UUID
    version: conint(ge=1)
    created_at: AwareDatetime
    updated_at: AwareDatetime
    name: constr(min_length=1, max_length=200)
    starts_on: date
    ends_on: date
    store_ids: list[UUID] = Field(..., max_length=1000, min_length=1)
    agreement_media_id: UUID | None
    archived: bool
    draft_revision: conint(ge=1)
    extracted_rules: list[Rule] = Field(..., max_length=30, min_length=0)
    extraction_gaps: list[ExtractionGap] = Field(..., max_length=20, min_length=0)
    approved_policy: PolicyVersion | None


class ApprovePolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expected_version: conint(ge=1)
    rules: list[Rule] = Field(..., max_length=30, min_length=1)
    catalog_product_ids: list[UUID] = Field(..., max_length=25, min_length=1)


class VisitCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    store_id: UUID
    notes: constr(max_length=5000)


class VisitUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expected_version: conint(ge=1)
    notes: constr(max_length=5000)


class Status5(Enum):
    OPEN = 'OPEN'
    CLOSED = 'CLOSED'


class Visit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    workspace_id: UUID
    version: conint(ge=1)
    created_at: AwareDatetime
    updated_at: AwareDatetime
    store_id: UUID
    notes: constr(max_length=5000)
    visit_started_at: AwareDatetime
    status: Status5
    before_media_ids: list[UUID] = Field(..., max_length=10, min_length=0)
    after_media_ids: list[UUID] = Field(..., max_length=10, min_length=0)
    active_investigation_id: UUID | None
    report_ids: list[UUID] = Field(..., max_length=100, min_length=0)


class NullReason(RootModel[constr(min_length=1, max_length=500)]):
    root: constr(min_length=1, max_length=500)


class FormulaVersion(Enum):
    peer_gap_v1 = 'peer_gap_v1'


class Metrics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sales_delta: constr(pattern=r'^-?\d+(\.\d+)?$') | None
    peer_growth: constr(pattern=r'^-?\d+(\.\d+)?$') | None
    expected_units: constr(pattern=r'^-?\d+(\.\d+)?$') | None
    opportunity_proxy: constr(pattern=r'^\d+\.\d{2}$') | None
    currency: Currency
    prior_start: date
    prior_end: date
    current_start: date
    current_end: date
    peer_store_ids: list[UUID] = Field(..., max_length=1000, min_length=0)
    null_reasons: list[NullReason] = Field(..., max_length=20, min_length=0)
    formula_version: FormulaVersion
    evidence_ids: list[UUID] = Field(..., max_length=100, min_length=0)


class Readines(RootModel[constr(min_length=1, max_length=500)]):
    root: constr(min_length=1, max_length=500)


class Freshness(Enum):
    CURRENT = 'CURRENT'
    STALE = 'STALE'
    MISSING = 'MISSING'


class StoreHealth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    store: Store
    metrics: Metrics | None
    readiness: list[Readines] = Field(..., max_length=20, min_length=0)
    freshness: Freshness


class Kind6(Enum):
    OBSERVATION = 'OBSERVATION'
    POLICY = 'POLICY'
    METRIC = 'METRIC'
    HYPOTHESIS = 'HYPOTHESIS'


class Claim(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    kind: Kind6
    text: constr(min_length=1, max_length=800)
    evidence_ids: list[UUID] = Field(..., max_length=30, min_length=1)


class Kind7(Enum):
    REPLENISH = 'REPLENISH'
    RESTORE_FACINGS = 'RESTORE_FACINGS'
    INSTALL_DISPLAY = 'INSTALL_DISPLAY'
    CHECK_STOCK = 'CHECK_STOCK'
    REQUEST_SUPPLY = 'REQUEST_SUPPLY'
    RETAKE = 'RETAKE'


class RequiredZoneId(RootModel[constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$')]):
    root: constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$')


class Status6(Enum):
    OPEN = 'OPEN'
    CLAIMED_DONE = 'CLAIMED_DONE'
    VERIFIED = 'VERIFIED'


class Action(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    kind: Kind7
    rule_ids: list[UUID] = Field(..., max_length=30, min_length=0)
    claim_ids: list[UUID] = Field(..., max_length=20, min_length=1)
    evidence_ids: list[UUID] = Field(..., max_length=30, min_length=1)
    instruction: constr(min_length=1, max_length=1000)
    required_zone_ids: list[RequiredZoneId] = Field(..., max_length=10, min_length=0)
    status: Status6


class Status7(Enum):
    OPEN = 'OPEN'
    CLAIMED_DONE = 'CLAIMED_DONE'


class ActionUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expected_version: conint(ge=1)
    status: Status7


class Hypothesis(Enum):
    EXECUTION = 'EXECUTION'
    SUPPLY_CONSTRAINT = 'SUPPLY_CONSTRAINT'
    UNEXPLAINED_DECLINE = 'UNEXPLAINED_DECLINE'
    NO_ISSUE = 'NO_ISSUE'
    INSUFFICIENT_EVIDENCE = 'INSUFFICIENT_EVIDENCE'


class Support(Enum):
    SUPPORTED = 'SUPPORTED'
    LIMITED = 'LIMITED'


class Alternative(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hypothesis: Hypothesis
    reason: constr(min_length=1, max_length=800)
    evidence_ids: list[UUID] = Field(..., max_length=30, min_length=0)


class UnresolvedQuestion(RootModel[constr(min_length=1, max_length=500)]):
    root: constr(min_length=1, max_length=500)


class Diagnosis(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hypothesis: Hypothesis
    support: Support
    summary: constr(min_length=1, max_length=1000)
    claims: list[Claim] = Field(..., max_length=20, min_length=1)
    alternatives: list[Alternative] = Field(..., max_length=3, min_length=0)
    unresolved_questions: list[UnresolvedQuestion] = Field(
        ..., max_length=20, min_length=0
    )


class InvestigationCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    store_id: UUID
    visit_id: UUID
    promotion_id: UUID
    media_ids: list[UUID] = Field(..., max_length=10, min_length=1)


class State(Enum):
    QUEUED = 'QUEUED'
    INVESTIGATING = 'INVESTIGATING'
    PROPOSED = 'PROPOSED'
    ACCEPTED = 'ACCEPTED'
    VERIFYING = 'VERIFYING'
    NEEDS_WORK = 'NEEDS_WORK'
    RESOLVED = 'RESOLVED'
    NO_ACTION = 'NO_ACTION'
    INCOMPLETE = 'INCOMPLETE'
    DISMISSED = 'DISMISSED'


class Investigation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    workspace_id: UUID
    version: conint(ge=1)
    created_at: AwareDatetime
    updated_at: AwareDatetime
    store_id: UUID
    visit_id: UUID
    promotion_id: UUID
    policy_version_id: UUID
    snapshot_id: UUID
    state: State
    snapshot_at: AwareDatetime
    metrics: Metrics | None
    diagnosis: Diagnosis | None
    actions: list[Action] = Field(..., max_length=3, min_length=0)
    plan_revision: conint(ge=0)
    accepted_at: AwareDatetime | None
    accepted_by: constr(min_length=1, max_length=200) | None
    current_job_id: UUID
    latest_verification_id: UUID | None
    policy_stale: bool


class Dismiss(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expected_version: conint(ge=1)
    reason: constr(min_length=1, max_length=1000)


class VerifyRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expected_version: conint(ge=1)
    after_media_ids: list[UUID] = Field(..., max_length=10, min_length=1)


class Result(Enum):
    PASS = 'PASS'
    FAIL = 'FAIL'
    UNKNOWN = 'UNKNOWN'


class Check(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rule_id: UUID
    result: Result
    evidence_ids: list[UUID] = Field(..., max_length=30, min_length=0)
    explanation: constr(min_length=1, max_length=1000)


class Result1(Enum):
    PASS = 'PASS'
    FAIL = 'FAIL'
    PARTIAL = 'PARTIAL'
    INCONCLUSIVE = 'INCONCLUSIVE'


class RequestedRetake(RootModel[constr(min_length=1, max_length=500)]):
    root: constr(min_length=1, max_length=500)


class Verification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    workspace_id: UUID
    version: conint(ge=1)
    created_at: AwareDatetime
    updated_at: AwareDatetime
    investigation_id: UUID
    plan_revision: conint(ge=1)
    after_media_ids: list[UUID] = Field(..., max_length=10, min_length=1)
    job_id: UUID
    checks: list[Check] = Field(..., max_length=30, min_length=0)
    result: Result1 | None
    requested_retakes: list[RequestedRetake] = Field(..., max_length=20, min_length=0)
    report_id: UUID | None


class Kind8(Enum):
    PHOTO = 'PHOTO'
    PDF = 'PDF'
    SALES_ROWS = 'SALES_ROWS'
    STOCK_ROWS = 'STOCK_ROWS'
    VISIT_NOTE = 'VISIT_NOTE'
    POLICY = 'POLICY'
    METRIC = 'METRIC'
    HUMAN = 'HUMAN'
    CATALOG = 'CATALOG'


class Freshness1(Enum):
    CURRENT = 'CURRENT'
    STALE = 'STALE'
    UNKNOWN = 'UNKNOWN'


class BoxItem(RootModel[conint(ge=0, le=1000)]):
    root: conint(ge=0, le=1000)


class Locator(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    media_id: UUID | None
    page: conint(ge=1) | None
    quote: constr(min_length=1, max_length=2000) | None
    box: list[BoxItem] | None
    row_ids: list[UUID] = Field(..., max_length=10000, min_length=0)
    batch_ids: list[UUID] = Field(..., max_length=1000, min_length=0)
    query_template_id: constr(min_length=1, max_length=100) | None
    query_job_id: constr(min_length=1, max_length=200) | None
    query_parameters: dict[str, str | float | bool | None]


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    investigation_id: UUID
    kind: Kind8
    observed_at: AwareDatetime
    retrieved_at: AwareDatetime
    freshness: Freshness1
    summary: constr(min_length=1, max_length=1000)
    source_id: UUID
    source_sha256: constr(pattern=r'^[a-f0-9]{64}$')
    locator: Locator


class Outcome(Enum):
    PASS = 'PASS'
    FAIL = 'FAIL'
    PARTIAL = 'PARTIAL'
    INCONCLUSIVE = 'INCONCLUSIVE'
    NO_ACTION = 'NO_ACTION'


class Report(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    workspace_id: UUID
    visit_id: UUID
    investigation_id: UUID
    verification_id: UUID | None
    created_at: AwareDatetime
    outcome: Outcome
    summary: constr(min_length=1, max_length=3000)
    checks: list[Check] = Field(..., max_length=30, min_length=0)
    evidence_ids: list[UUID] = Field(..., max_length=1000, min_length=0)
    policy_version_id: UUID


class StoreList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Store] = Field(..., max_length=100, min_length=0)
    next_cursor: constr(min_length=1, max_length=500) | None


class LocationList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Location] = Field(..., max_length=100, min_length=0)
    next_cursor: constr(min_length=1, max_length=500) | None


class ProductList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Product] = Field(..., max_length=100, min_length=0)
    next_cursor: constr(min_length=1, max_length=500) | None


class ImportList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Import] = Field(..., max_length=100, min_length=0)
    next_cursor: constr(min_length=1, max_length=500) | None


class PromotionList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Promotion] = Field(..., max_length=100, min_length=0)
    next_cursor: constr(min_length=1, max_length=500) | None


class PolicyVersionList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[PolicyVersion] = Field(..., max_length=100, min_length=0)
    next_cursor: constr(min_length=1, max_length=500) | None


class VisitList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Visit] = Field(..., max_length=100, min_length=0)
    next_cursor: constr(min_length=1, max_length=500) | None


class InvestigationList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Investigation] = Field(..., max_length=100, min_length=0)
    next_cursor: constr(min_length=1, max_length=500) | None


class VerificationList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Verification] = Field(..., max_length=100, min_length=0)
    next_cursor: constr(min_length=1, max_length=500) | None


class EvidenceList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Evidence] = Field(..., max_length=100, min_length=0)
    next_cursor: constr(min_length=1, max_length=500) | None


class SnapshotToolInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    store_id: UUID
    snapshot_id: UUID


class PolicyToolInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    policy_version_id: UUID


class VisitHistoryToolInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    store_id: UUID
    snapshot_id: UUID
    limit: conint(ge=1, le=3)


class InspectImageToolInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    media_id: UUID
    reference_media_ids: list[UUID] = Field(..., max_length=100, min_length=1)
    zone_id: constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$')


class ExtractPolicyToolInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    media_id: UUID
    catalog_product_ids: list[UUID] = Field(..., max_length=25, min_length=1)
    store_ids: list[UUID] = Field(..., max_length=1000, min_length=1)


class PeerSales(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    store_id: UUID
    complete: bool
    prior_units: conint(ge=0) | None
    current_units: conint(ge=0) | None
    retailer: constr(min_length=1, max_length=200)
    region: constr(min_length=1, max_length=200)
    format: constr(min_length=1, max_length=80)
    currency: Currency
    promotion_id: UUID
    evidence_ids: list[UUID] = Field(..., max_length=100, min_length=0)


class Gap(RootModel[constr(min_length=1, max_length=500)]):
    root: constr(min_length=1, max_length=500)


class SalesContext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    snapshot_id: UUID
    store_id: UUID
    catalog_product_ids: list[UUID] = Field(..., max_length=25, min_length=1)
    prior_start: date
    prior_end: date
    current_start: date
    current_end: date
    complete: bool
    prior_units: conint(ge=0) | None
    current_units: conint(ge=0) | None
    prior_revenue: constr(pattern=r'^\d+\.\d{2}$') | None
    current_revenue: constr(pattern=r'^\d+\.\d{2}$') | None
    currency: Currency
    eligible_peers: list[PeerSales] = Field(..., max_length=1000, min_length=0)
    gaps: list[Gap] = Field(..., max_length=100, min_length=0)
    evidence_ids: list[UUID] = Field(..., max_length=1000, min_length=0)


class LocationType(Enum):
    BACKROOM = 'BACKROOM'
    DISTRIBUTOR = 'DISTRIBUTOR'


class Unit(Enum):
    UNIT = 'UNIT'
    CASE = 'CASE'


class Freshness2(Enum):
    CURRENT = 'CURRENT'
    STALE = 'STALE'


class StockItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    product_id: UUID
    location_id: UUID
    location_type: LocationType
    quantity: conint(ge=0)
    unit: Unit
    units_normalized: conint(ge=0)
    observed_at: AwareDatetime
    freshness: Freshness2
    evidence_id: UUID


class MissingItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    product_id: UUID
    location_type: LocationType


class StockContext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    snapshot_id: UUID
    store_id: UUID
    items: list[StockItem] = Field(..., max_length=100, min_length=0)
    missing: list[MissingItem] = Field(..., max_length=100, min_length=0)


class Visit1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visit_id: UUID
    visited_at: AwareDatetime
    notes: constr(max_length=5000)
    evidence_ids: list[UUID] = Field(..., max_length=100, min_length=0)


class VisitHistoryContext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    snapshot_id: UUID
    store_id: UUID
    visits: list[Visit1] = Field(..., max_length=3, min_length=0)


class Status8(Enum):
    OK = 'OK'
    MISSING = 'MISSING'
    STALE = 'STALE'
    ERROR = 'ERROR'


class Error1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: constr(min_length=1, max_length=80)
    message: constr(min_length=1, max_length=500)
    retryable: bool


class ToolEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status8
    data: dict[str, Any] | None
    evidence_ids: list[UUID] = Field(..., max_length=1000, min_length=0)
    as_of: AwareDatetime
    error: Error1 | None
